FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./apps/web ./apps/web
COPY ./packages/db/prisma ./packages/db/prisma

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN bun install

RUN bun turbo run db:generate 
RUN bun turbo run build 

EXPOSE 3000

CMD ["bun", "run", "start:web"]
