FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./apps/web ./apps/web
COPY ./prisma ./prisma

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./tsconfig.json ./tsconfig.json

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

RUN bun install

RUN bun turbo run db:generate --filter=web
RUN bun turbo run build --filter=web

EXPOSE 3000

CMD ["bun", "run", "start:web"]
